# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WAP-wmls
version:      1.03
version_from: node.pm
installdirs:  site
requires:
    I18N::Charset:                 1.15
    Unicode::Map:                  0
    Unicode::String:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
